/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registrar_Caja_Chica;
//Conectar base de datos
import Controlador.CajaChicaControlador;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

// se agrego automaticamente no se para que sirve
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sebas
 */
public class Cuadro_Registrar_Caja_Chica extends javax.swing.JFrame {
    /**
     * Creates new form Registrar_Caja_Chica
     */
    
    public Cuadro_Registrar_Caja_Chica() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ccaja = new javax.swing.JTextField();
        departamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        minicial = new javax.swing.JTextField();
        fcrea = new javax.swing.JTextField();
        tcaja = new javax.swing.JComboBox<>();
        registrar1 = new javax.swing.JButton();

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Registro de Caja Chica");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 410, 70);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Codigo de Caja Chica");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 260, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Fecha de Creacion");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 160, 220, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Tipo de caja Chica");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 210, 230, 32);

        ccaja.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ccaja.setForeground(new java.awt.Color(102, 255, 102));
        ccaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccajaActionPerformed(evt);
            }
        });
        getContentPane().add(ccaja);
        ccaja.setBounds(480, 90, 290, 40);

        departamento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administracion", "RR.SS", "Viajes;etc" }));
        departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoActionPerformed(evt);
            }
        });
        getContentPane().add(departamento);
        departamento.setBounds(480, 330, 160, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Monto Inicial ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 260, 260, 32);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Departamento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 320, 260, 32);

        minicial.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        minicial.setForeground(new java.awt.Color(102, 255, 102));
        minicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minicialActionPerformed(evt);
            }
        });
        getContentPane().add(minicial);
        minicial.setBounds(480, 260, 290, 40);

        fcrea.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fcrea.setForeground(new java.awt.Color(102, 255, 102));
        fcrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcreaActionPerformed(evt);
            }
        });
        getContentPane().add(fcrea);
        fcrea.setBounds(480, 150, 290, 40);

        tcaja.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tcaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caja Chica 1(Gastos importantes)", "Caja Chica 2(Gastos Varios)" }));
        tcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcajaActionPerformed(evt);
            }
        });
        getContentPane().add(tcaja);
        tcaja.setBounds(480, 210, 310, 30);

        registrar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registrar1.setText("REGISTRAR");
        registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(registrar1);
        registrar1.setBounds(480, 390, 210, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccajaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ccajaActionPerformed

    private void departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /* Mensaje_Final newframe= new Mensaje_Final();
        //haceer visible la nueva ventana
        newframe.setVisible(true);
        /*escondeer ventana anterior
        this.setVisible(false);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void minicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minicialActionPerformed

    private void fcreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcreaActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_fcreaActionPerformed

    private void tcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcajaActionPerformed

    private void registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar1ActionPerformed

        try {
        RegistroCChica rcc = new RegistroCChica();
        //crea una instancia de simpledate con la forma a ingresar dia mes año
        SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
        //Configurado para que no acepte fechas invalidas
        fecha.setLenient(false);
        //valida la fecha
        Date fechaCreacion = fecha.parse(fcrea.getText());
        CajaChicaControlador caja = new CajaChicaControlador();
        
        rcc.setCcaja((ccaja.getText())); 
        rcc.setFcrea((fcrea.getText())); 
        rcc.setTcaja(tcaja.getSelectedItem().toString());
        rcc.setDepart(departamento.getSelectedItem().toString());
        rcc.setMinicial(Double.parseDouble(minicial.getText()));

        caja.insertar(rcc);

        
        
        JOptionPane.showMessageDialog(null, "Datos registrados exitosamente.");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error en los datos. Asegúrese de ingresar números válidos donde corresponda.");
    }   catch (ParseException e) {
            Logger.getLogger(Cuadro_Registrar_Caja_Chica.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_registrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuadro_Registrar_Caja_Chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuadro_Registrar_Caja_Chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuadro_Registrar_Caja_Chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuadro_Registrar_Caja_Chica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuadro_Registrar_Caja_Chica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccaja;
    private javax.swing.JComboBox<String> departamento;
    private javax.swing.JTextField fcrea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField minicial;
    private javax.swing.JButton registrar1;
    private javax.swing.JComboBox<String> tcaja;
    // End of variables declaration//GEN-END:variables
}
